name: "ROS Rootfs Layout Settings"
stages:
  initramfs:
    - if: '[ ! -f /run/cos/recovery_mode ]'
      commands:
      - |
        target=/usr/local/.ros-state

        # Always want the latest update of systemd conf from the image
        mkdir -p ${target}/etc/systemd/
        rsync -av /etc/systemd/ ${target}/etc/systemd/

        if [ ! -e /usr/local/etc/hostname ]; then
          echo rancher-${RANDOM} > /usr/local/etc/hostname
        fi
        ln -sf /usr/local/etc/hostname /etc/hostname

        # Only populate ssh conf once
        if [ ! -e ${target}/etc/ssh ]; then
          mkdir -p ${target}/etc/ssh/
          rsync -a /etc/ssh/ ${target}/etc/ssh/
        fi

        sed -i '/overlay \/home /d' /etc/fstab
        sed -i '/overlay \/opt /d' /etc/fstab
        nsenter -m -t 1 -- umount /sysroot/home
        nsenter -m -t 1 -- umount /sysroot/opt

        # setup directories as persistent
        for i in root opt home var/lib/rancher var/lib/kubelet etc/systemd etc/rancher etc/ssh usr/libexec var/log var/lib/wicked; do
          mkdir -p ${target}/$i /$i
          nsenter -m -t 1 -- mount /sysroot${target}/$i /sysroot/$i -t none -o bind
        done

        # This is hidden so that if you run some selinux label checking or relabeling the bind
        # mount won't screw up things.  If you have two files at different paths they will get
        # labeled with two different labels.
        mkdir -p ${target}/empty
        nsenter -m -t 1 -- mount /sysroot${target}/empty /sysroot${target} -o bind,ro

        # ensure /var/log/journal exists so it's labeled correctly
        nsenter -m -t 1 -- mkdir -p /sysroot/var/log/journal
  initramfs.after:
    - if: '[ ! -f /run/cos/recovery_mode ]'
      commands:
      - restorecon -R -v /etc /home /opt /var /usr/local /tmp /srv /root
  fs.before:
    - name: "Pull data from provider (local)"
      datasource:
        providers: ["aws", "gcp", "openstack", "cdrom"]
        path: "/oem"
    - if: '[ ! -f /run/cos/recovery_mode ]'
      commands:
      - restorecon -R -v /etc /home /opt /var /usr/local /tmp /srv /root
  rootfs.after:
    - if: '[ ! -f /run/cos/recovery_mode ] && [ ! -f /run/cos/live_mode ]'
      name: "Grow persistent"
      layout:
        device:
          label: COS_PERSISTENT
        expand_partition:
          size: 0
  fs.before:
    - if: '[ ! -f "/run/cos/recovery_mode" ] && [ ! -f /run/cos/live_mode ]'
      name: "Grow persistent fs"
      commands:
      - resize2fs $(blkid -L COS_PERSISTENT)
