name: "Default user"
stages:
   initramfs:
   - name: "Setup groups"
     ensure_entities:
     - entity: |
         kind: "group"
         group_name: "admin"
         password: "x"
         gid: 900
     - entity: |
         kind: "group"
         group_name: "rancher"
         password: "x"
         gid: 1000
   - name: "Setup users"
     users:
       rancher:
         name: "rancher"
         passwd: "$6$mL4eOZ/wHV4MtjaZ$ASiwT66Yj9I/61cc7/vzdl6I8p5xK11Yn1EtSEO1CytZszfmP3R5iA05g0voxfZ5Dkj5BYdicE8lLnf3atbzE/"
         groups: 
         - "admin"
         - "systemd-journal"
         primary_group: "rancher"
         shell: /bin/bash
         homedir: "/home/rancher"
     #ensure_entities:
     #- entity: |
     #     kind: "shadow"
     #     username: "root"
     #     password: "$6$g9DDJRDNRS8MEzhH$w6Cn6PNzFnUVnatwRbNoLk6etanvAbcxUzfYlQcj6y/JLGq3Yrl7wXi6SkMzp1/tEM3NheMr5fH8.92NdiaB/0"
   - name: "Setup sudo"
     files:
     - path: "/etc/sudoers"
       owner: 0
       group: 0
       permsisions: 0600
       content: |
          Defaults always_set_home
          Defaults secure_path="/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin"
          Defaults env_reset
          Defaults env_keep = "LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_ATIME LC_ALL LANGUAGE LINGUAS XDG_SESSION_COOKIE"
          Defaults !insults
          root ALL=(ALL) ALL
          %admin ALL=(ALL) NOPASSWD: ALL
          @includedir /etc/sudoers.d
