name: "Rancherd"
stages:
   initramfs:
     - name: "Rancherd"
       commands:
       - |
         if grep -q root=live:CDLABEL=COS_LIVE /proc/cmdline || [ -n "$(blkid -L COS_SYSTEM)" ]; then
            systemctl disable rancherd.service
         else
            systemctl enable rancherd.service
         fi
